#! /usr/bin/env sh

riverctl declare-mode float
riverctl map normal Super G enter-mode float
riverctl map float Super G enter-mode normal

riverctl map -repeat float Control Down move down 1
riverctl map -repeat float Control H move left 1
riverctl map -repeat float Control J move down 1
riverctl map -repeat float Control K move up 1
riverctl map -repeat float Control L move right 1
riverctl map -repeat float Control Left move left 1
riverctl map -repeat float Control Right move right 1
riverctl map -repeat float Control Up move up 1
riverctl map -repeat float Control+Alt Down move down 25
riverctl map -repeat float Control+Alt H move left 25
riverctl map -repeat float Control+Alt J move down 25
riverctl map -repeat float Control+Alt K move up 25
riverctl map -repeat float Control+Alt L move right 25
riverctl map -repeat float Control+Alt Left move left 25
riverctl map -repeat float Control+Alt Right move right 25
riverctl map -repeat float Control+Alt Up move up 25
riverctl map -repeat float Shift Down resize vertical -1
riverctl map -repeat float Shift H resize horizontal -1
riverctl map -repeat float Shift J resize vertical 1
riverctl map -repeat float Shift K resize vertical -1
riverctl map -repeat float Shift L resize horizontal 1
riverctl map -repeat float Shift Left resize horizontal -1
riverctl map -repeat float Shift Right resize horizontal 1
riverctl map -repeat float Shift Up resize vertical 1
riverctl map -repeat float Shift+Alt Down resize vertical -25
riverctl map -repeat float Shift+Alt H resize horizontal -25
riverctl map -repeat float Shift+Alt J resize vertical 25
riverctl map -repeat float Shift+Alt K resize vertical -25
riverctl map -repeat float Shift+Alt L resize horizontal 25
riverctl map -repeat float Shift+Alt Left resize horizontal -25
riverctl map -repeat float Shift+Alt Right resize horizontal 25
riverctl map -repeat float Shift+Alt Up resize vertical 25
riverctl map float None Comma send-to-output previous
riverctl map float None G toggle-float
riverctl map float None H focus-view previous
riverctl map float None L focus-view next
riverctl map float None Left focus-view previous
riverctl map float None P set-vitew-tags "$ALL_TAGS"
riverctl map float None Period send-to-output next
riverctl map float None Right focus-view next
