image: alpine/edge
triggers:
  - action: email
    condition: failure
    to: Aiden Langley <aiden@nedia.dev>
secrets:
  - a77b73f8-c9ba-4789-b7ca-63a9aec01163
tasks:
  - mirror: |
      cd dots
      git remote add gh git@github.com:aidenlangley/dots.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push gh --tags && git push gh main
