complete -c nedots -n "__fish_use_subcommand" -s c -l config -d 'Custom config file' -r
complete -c nedots -n "__fish_use_subcommand" -s v -l verbose -d 'More output per occurrence'
complete -c nedots -n "__fish_use_subcommand" -s q -l quiet -d 'Less output per occurrence'
complete -c nedots -n "__fish_use_subcommand" -s h -l help -d 'Print help information'
complete -c nedots -n "__fish_use_subcommand" -s V -l version -d 'Print version information'
complete -c nedots -n "__fish_use_subcommand" -f -a "backup" -d 'Backup local configuration files/(ne)dots'
complete -c nedots -n "__fish_use_subcommand" -f -a "clean" -d 'Clean up `dots` & `backups`. Example: `nedots clean -db` to clean both'
complete -c nedots -n "__fish_use_subcommand" -f -a "completions"
complete -c nedots -n "__fish_use_subcommand" -f -a "init" -d 'Initialize `nedots`'
complete -c nedots -n "__fish_use_subcommand" -f -a "install" -d 'Install filese & directories from {root}/{dots_dir}/{source} to $HOME/{source}'
complete -c nedots -n "__fish_use_subcommand" -f -a "sync"
complete -c nedots -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c nedots -n "__fish_seen_subcommand_from backup" -s v -l verbose -d 'More output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from backup" -s q -l quiet -d 'Less output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from backup" -s h -l help -d 'Print help information'
complete -c nedots -n "__fish_seen_subcommand_from clean" -s d -l dots -d 'Clean up `dots`'
complete -c nedots -n "__fish_seen_subcommand_from clean" -s b -l backups -d 'Clean up `backups`'
complete -c nedots -n "__fish_seen_subcommand_from clean" -s y -l assumeyes -d 'Won\'t prompt you to confirm the operation when cleaning'
complete -c nedots -n "__fish_seen_subcommand_from clean" -s v -l verbose -d 'More output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from clean" -s q -l quiet -d 'Less output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from clean" -s h -l help -d 'Print help information'
complete -c nedots -n "__fish_seen_subcommand_from completions" -s v -l verbose -d 'More output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from completions" -s q -l quiet -d 'Less output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Print help information'
complete -c nedots -n "__fish_seen_subcommand_from init" -s f -l from-user -d 'Migrating files from this user' -r
complete -c nedots -n "__fish_seen_subcommand_from init" -s v -l verbose -d 'More output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from init" -s q -l quiet -d 'Less output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from init" -s h -l help -d 'Print help information'
complete -c nedots -n "__fish_seen_subcommand_from install" -s v -l verbose -d 'More output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from install" -s q -l quiet -d 'Less output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from install" -s h -l help -d 'Print help information'
complete -c nedots -n "__fish_seen_subcommand_from sync" -s g -l gather -d 'Gather dots before syncing'
complete -c nedots -n "__fish_seen_subcommand_from sync" -s n -l nopush -d 'Don\'t push to remote, useful for testing'
complete -c nedots -n "__fish_seen_subcommand_from sync" -s v -l verbose -d 'More output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from sync" -s q -l quiet -d 'Less output per occurrence'
complete -c nedots -n "__fish_seen_subcommand_from sync" -s h -l help -d 'Print help information'
complete -c nedots -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from backup; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "backup" -d 'Backup local configuration files/(ne)dots'
complete -c nedots -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from backup; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "clean" -d 'Clean up `dots` & `backups`. Example: `nedots clean -db` to clean both'
complete -c nedots -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from backup; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "completions"
complete -c nedots -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from backup; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "init" -d 'Initialize `nedots`'
complete -c nedots -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from backup; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "install" -d 'Install filese & directories from {root}/{dots_dir}/{source} to $HOME/{source}'
complete -c nedots -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from backup; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "sync"
complete -c nedots -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from backup; and not __fish_seen_subcommand_from clean; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from install; and not __fish_seen_subcommand_from sync; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
