#! /usr/bin/env sh

riverctl input "2:14:ETPS/2_Elantech_Touchpad" tap enabled
riverctl input "2:14:ETPS/2_Elantech_Touchpad" disable-while-typing enabled
riverctl input "1133:16514:Logitech_MX_Master_3" accel-profile flat
