remote: git@git.sr.ht:~nedia/dots
dots:
  - .cobra.yaml
  - .config/bat
  - .config/btop
  - .config/chromium-flags.conf
  - .config/code-flags.conf
  - .config/dunst
  - .config/electron-flags.conf
  - .config/fish
  - .config/flutter
  - .config/fontconfig
  - .config/foot
  - .config/gamemode.ini
  - .config/gammastep
  - .config/gtk-3.0
  - .config/kitty
  - .config/lazygit
  - .config/nedots
  - .config/qalculate
  - .config/remmina
  - .config/river
  - .config/systemd
  - .config/way-displays
  - .config/yambar
  - .gitconfig
  - .gtkrc-2.0
  - .local/bin/brightness
  - .local/bin/colorpicker
  - .local/bin/cputemp
  - .local/bin/disk
  - .local/bin/idle
  - .local/bin/idle-toggle
  - .local/bin/iommu-groups
  - .local/bin/mem
  - .local/bin/river-enter-mode
  - .local/bin/river-watch-mode
  - .local/bin/swww-refresh
  - .local/bin/vol
  - .profile
  - .yarnrc.yml
  - /usr/local/bin/river-run
  - /usr/local/bin/waylock-run
  - package.json
repos:
  - remote: git@git.sr.ht:~nedia/config.nvim
    path: .config/nvim
  - remote: git@git.sr.ht:~nedia/vm
    path: .vm
