# Colours
# IDE highlights the colours so we want it this way
# yamllint disable rule:comments
# yamllint disable rule:document-start
bg: &bg 282828ff #28282890
fg: &fg ebdbb2ff #ebdbb2ff
dim: &dim 3c3836ff #3c3836ff
border: &border 504945ff #504945ff
highlight: &highlight d8a657ff #d8a657ff
urgent: &urgent ea6962ff #ea6962ff
affirm: &affirm a9b665ff #a9b665ff
# yamllint enable

# Fonts
font: &font "JetBrains Mono:pixelsize=12"
bold: &bold "JetBrains Mono:style=Bold:pixelsize=12"
symbols: &symbols "Symbols Nerd Font:pixelsize=14"

# Spacing
spacing: &spacing 4
margin: &margin 12

# Network
net_poll_interval: &net_poll_interval 1
dl_speed: &dl_speed "{dl-speed:mb} Mbps"
net_down: &net_down {text: "", font: *symbols, foreground: *highlight}

bar:
  monitor: "HDMI-A-1"
  location: "bottom"
  height: 32
  spacing: *spacing
  right-margin: *margin
  background: *bg
  foreground: *fg
  border:
    top-width: 1
    color: *border
  font: *font

  left:
    # Highlights windows that are tagged
    - river:
        anchors:
          - padding: &river_padding 6
          - base: &river_base
              margin: 4
              conditions:
                ~visible:
                  map:
                    conditions:
                      ~occupied: {empty: {}}
                      occupied:
                        - string:
                            text: "{id}"
                            font: *bold
                            margin: *river_padding
                urgent:
                  - string:
                      text: "{id}"
                      font: *bold
                      margin: *river_padding
                      foreground: *bg
                focused:
                  - string:
                      text: "{id}"
                      font: *bold
                      margin: *river_padding
                      foreground: *bg
        content:
          map:
            conditions:
              ~visible:
                map:
                  conditions:
                    ~occupied: {empty: {}}
                    occupied:
                      map:
                        <<: *river_base
                        deco: {background: {color: *dim}}
              urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: *urgent}}
              focused:
                map:
                  <<: *river_base
                  deco:
                    stack:
                      - background: {color: *fg}
                      - overline: {color: *border, size: 1}

    - script:
        path: "/home/aiden/.local/bin/cpu"
        args: [1]
        anchors:
          - icon: &cpu_icon ""
          - usage: &cpu_usage "{cpu}%"
        content:
          map:
            margin: *spacing
            default:
              - string: {text: *cpu_icon, font: *symbols, margin: *spacing}
              - string: {text: *cpu_usage}
            conditions:
              cpu >= 60:
                - string:
                    text: *cpu_icon
                    font: *symbols
                    foreground: *highlight
                    margin: *spacing
                - string:
                    text: *cpu_usage
                    font: *bold
                    foreground: *highlight
              cpu >= 80:
                - string:
                    text: *cpu_icon
                    font: *symbols
                    foreground: *urgent
                    margin: *spacing
                - string:
                    text: *cpu_usage
                    font: *bold
                    foreground: *urgent

    - script:
        path: "/home/aiden/.local/bin/cputemp"
        args: [8]
        anchors: {temp: &temp "{temp}°C"}
        content:
          ramp:
            tag: temp
            min: 30
            max: 90
            items:
              - list:
                  items:
                    - string: {text: "", font: *symbols, margin: *spacing}
                    - string: {text: *temp}
              - list:
                  items:
                    - string: {text: "", font: *symbols, margin: *spacing}
                    - string: {text: *temp}
              - list:
                  items:
                    - string: {text: "", font: *symbols, margin: *spacing}
                    - string: {text: *temp}
              - list:
                  items:
                    - string: {text: "", font: *symbols, margin: *spacing}
                    - string: {text: *temp}
              - list:
                  items:
                    - string:
                        text: ""
                        font: *symbols
                        margin: *spacing
                        foreground: *highlight
                    - string:
                        text: *temp
                        font: *bold
                        foreground: *highlight
              - list:
                  items:
                    - string:
                        text: ""
                        font: *symbols
                        margin: *spacing
                        foreground: *urgent
                    - string:
                        text: *temp
                        font: *bold
                        foreground: *urgent

    - script:
        path: "/home/aiden/.local/bin/mem"
        args: ["mem", 2]
        anchors:
          - icon: &mem_icon ""
          - used: &mem_used "{used} MiB"
        content:
          map:
            margin: *spacing
            default:
              - string: {text: *mem_icon, font: *symbols, margin: *spacing}
              - string: {text: *mem_used}
            conditions:
              percent >= 60:
                - string:
                    text: *mem_icon
                    font: *symbols
                    foreground: *highlight
                    margin: *spacing
                - string:
                    text: *mem_used
                    font: *bold
                    foreground: *highlight
              percent >= 80:
                - string:
                    text: *mem_icon
                    font: *symbols
                    foreground: *urgent
                    margin: *spacing
                - string:
                    text: *mem_used
                    font: *bold
                    foreground: *urgent

    - script:
        path: "/home/aiden/.local/bin/mem"
        args: ["swap", 2]
        anchors:
          - icon: &swap_icon ""
          - used: &swap_used "{used} MiB"
        content:
          map:
            margin: *spacing
            conditions:
              percent > 0:
                - string:
                    text: *swap_icon
                    font: *symbols
                    margin: *spacing
                - string: { text: *swap_used }
              percent >= 60:
                - string:
                    text: *swap_icon
                    font: *symbols
                    foreground: *highlight
                    margin: *spacing
                - string:
                    text: *swap_used
                    font: *bold
                    foreground: *highlight
              percent >= 80:
                - string:
                    text: *swap_icon
                    font: *symbols
                    foreground: *urgent
                    margin: *spacing
                - string:
                    text: *swap_used
                    font: *bold
                    foreground: *urgent

  center:
    # Displays window title
    - river:
        title: {string: {text: "{title}", max: 64}}
        content: {empty: {}}

  right:
    - network:
        name: "enp2s0"
        poll-interval: *net_poll_interval
        content:
          map:
            conditions:
              ~carrier: {empty: {}}
              carrier:
                map:
                  default:
                    - string: {text: *dl_speed, margin: *spacing}
                    - string: {text: "", font: *symbols}
                  conditions:
                    state == "down": {string: *net_down}

    - network:
        name: "wlp3s0"
        poll-interval: *net_poll_interval
        content:
          map:
            conditions:
              ~carrier: {empty: {}}
              carrier:
                map:
                  default:
                    - string: {text: *dl_speed, margin: *spacing}
                    - string: {text: "|"}
                    - string: {text: "{ssid}", margin: *spacing}
                    - string: {text: "﬉", font: *symbols}
                  conditions:
                    state == "down": {string: *net_down}

    - script:
        path: "/home/aiden/.local/bin/vol"
        poll-interval: 1
        content:
          map:
            on-click:
              left: "/home/aiden/.local/bin/vol toggle"
              right: "pavucontrol"
              wheel-up: "/home/aiden/.local/bin/vol up"
              wheel-down: "/home/aiden/.local/bin/vol down"
            default:
              ramp:
                tag: vol
                min: 0
                max: 100
                items:
                  - list:
                      items:
                        - string: {text: "{vol}%", margin: *spacing}
                        - string: {text: "", font: *symbols}
                  - list:
                      items:
                        - string: {text: "{vol}%", margin: *spacing}
                        - string: {text: "", font: *symbols}
                  - list:
                      items:
                        - string: {text: "{vol}%", margin: *spacing}
                        - string: {text: "墳", font: *symbols}
                  - list:
                      items:
                        - string: {text: "{vol}%", margin: *spacing}
                        - string: {text: "", font: *symbols}
            conditions:
              mute:
                - list:
                    items:
                      - string:
                          text: "muted"
                          foreground: *border
                          margin: *spacing
                      - string:
                          text: "婢"
                          font: *symbols
                          foreground: *border

    - clock:
        time-format: "%H:%M:%S"
        content:
          - string: {text: "{time}", font: *bold, margin: *spacing}
          - string: {text: "", font: *symbols}

    - battery:
        name: "BAT0"
        poll-interval: 30
        anchors:
          capacity: &capacity "{capacity}%"
          estimate: &estimate "{estimate}"
        content:
          map:
            default:
              ramp:
                tag: "capacity"
                min: 0
                max: 100
                items:
                  - list:
                      items:
                        - string:
                            text: *capacity
                            font: *bold
                            foreground: *urgent
                            margin: *spacing
                        - string:
                            text: ""
                            font: *symbols
                            foreground: *urgent
                  - list:
                      items:
                        - string:
                            text: *capacity
                            font: *bold
                            foreground: *urgent
                            margin: *spacing
                        - string:
                            text: ""
                            font: *symbols
                            foreground: *urgent
                  - list:
                      items:
                        - string: {text: *capacity, margin: *spacing}
                        - string:
                            text: ""
                            font: *symbols
                            foreground: *highlight
                  - list:
                      items:
                        - string: {text: *capacity, margin: *spacing}
                        - string:
                            text: ""
                            font: *symbols
                            foreground: *highlight
                  - list:
                      items:
                        - string: {text: *capacity, margin: *spacing}
                        - string: {text: "", font: *symbols}
                  - list:
                      items:
                        - string: {text: *capacity, margin: *spacing}
                        - string: {text: "", font: *symbols}
                  - list:
                      items:
                        - string: {text: *capacity, margin: *spacing}
                        - string: {text: "", font: *symbols}
                  - list:
                      items:
                        - string: {text: *capacity, margin: *spacing}
                        - string: {text: "", font: *symbols}
                  - list:
                      items:
                        - string: {text: *capacity, margin: *spacing}
                        - string: {text: "", font: *symbols}
                  - list:
                      items:
                        - string: {text: *capacity, margin: *spacing}
                        - string: {text: "", font: *symbols}
                  - list:
                      items:
                        - string: {text: *capacity, margin: *spacing}
                        - string: {text: "", font: *symbols}
            conditions:
              state == "charging":
                ramp:
                  tag: "capacity"
                  min: 0
                  max: 100
                  items:
                    - list:
                        items:
                          - string: {text: *estimate, margin: *spacing}
                          - string:
                              text: ""
                              font: *symbols
                              foreground: *urgent
                    - list:
                        items:
                          - string: {text: *estimate, margin: *spacing}
                          - string:
                              text: ""
                              font: *symbols
                              foreground: *highlight
                    - list:
                        items:
                          - string: {text: *estimate, margin: *spacing}
                          - string: {text: "", font: *symbols}
                    - list:
                        items:
                          - string: {text: *estimate, margin: *spacing}
                          - string: {text: "", font: *symbols}
                    - list:
                        items:
                          - string: {text: *estimate, margin: *spacing}
                          - string: {text: "", font: *symbols}
                    - list:
                        items:
                          - string: {text: *estimate, margin: *spacing}
                          - string: {text: "", font: *symbols}
                    - list:
                        items:
                          - string: {text: *estimate, margin: *spacing}
                          - string: {text: "", font: *symbols}
                    - list:
                        items:
                          - string:
                              text: ""
                              font: *symbols
                              foreground: *affirm
              state == "full":
                - string: {text: "", font: *symbols, foreground: *affirm}
