#! /usr/bin/env sh

riverctl background-color 0x002b36
riverctl border-color-focused 0x504945
riverctl border-color-unfocused 0x282828
riverctl border-color-urgent 0xea6962
riverctl border-width 1

riverctl attach-mode bottom
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change
riverctl set-repeat 50 300

riverctl xcursor-theme Adwaita
riverctl default-layout rivertile

riverctl keyboard-layout "nz,us"
