#! /usr/bin/env bash

ALL_TAGS="$(qalc -t "(2 ^ 32) - 1")"
export ALL_TAGS

source "${HOME}"/.config/river/keymaps/normal
source "${HOME}"/.config/river/keymaps/float
# source "${HOME}"/.config/river/keymaps/tags/docs
# source "${HOME}"/.config/river/keymaps/tags/scratch

source "${HOME}"/.config/river/inputs
source "${HOME}"/.config/river/rules
source "${HOME}"/.config/river/config

# Set our wallpaper but let swww take over later
swaybg --image "${HOME}"/Pictures/Wallpapers/Desktop/wallhaven-y89del.png --mode fill &

# Import environment variables so that systemd runs smooth
systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# GTK hangs without this
dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Fire off child services by starting their target
systemctl --user start wayland.target

# This handles layout
rivertile -view-padding 1 -outer-padding 2 -main-ratio 0.5
