#! /usr/bin/env sh

riverctl input pointer-1133-16500-Logitech_G305 accel-profile flat
riverctl input pointer-1133-16500-Logitech_G305 pointer-accel -0.3
riverctl input pointer-1133-45091-MX_Master_3 events enabled
riverctl input pointer-1133-45091-MX_Master_3 accel-profile flat
riverctl input pointer-1133-49291-Logitech_G502_HERO_Gaming_Mouse accel-profile flat
riverctl input pointer-1133-49291-Logitech_G502_HERO_Gaming_Mouse pointer-accel -0.5
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad disable-while-typing enabled
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad tap enabled
