#! /usr/bin/env sh

# Mouse
riverctl input pointer-1133-16514-Logitech_MX_Master_3 events enabled
riverctl input pointer-1133-16514-Logitech_MX_Master_3 accel-profile flat

# Trackpad
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad disable-while-typing enabled
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad tap enabled
