#! /usr/bin/env fish

# Kick off the other programs - systemd service files start most things
systemctl --user start bspwm.target

bspc monitor DP-1 -d I II III IV V
# bspc monitor HDMI-1 -d V

# Options are: longest_side, alternate, spiral
bspc config automatic_scheme longest_side
bspc config split_ratio 0.5
bspc config directional_focus_tightness high
bspc config window_gap 4
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Windows
bspc config border_width 1
bspc config normal_border_color '#282828'
bspc config active_border_color '#3c3836'
bspc config focused_border_color '#504945'
bspc config presel_feedback_color '#e78a4e'

# Focus
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

# Rearranging monitors to ensure they're the way we want things
# bspc wm -O DP-1 HDMI-1

# # Games & large applications go to 4, a floating desktop
# set to_four Battle.net.exe \
#     'Gimp-*' \
#     Inkscape \
#     Krita \
#     Lutris \
#     Steam \
#     Vampire_Survivors

# ## Send them all to desktop IV
# for prog in $to_four
#     bspc rule -a $prog desktop='IV' follow=on center=on
# end

# Float & center all widgets / settings
set float Blueman-manager \
    Blueman-services \
    Flameshot \
    Grub-customizer \
    Lightdm-gtk-greeter-settings \
    Nemo \
    Nm-connection-editor \
    Pavucontrol \
    Qalculate-gtk

## Float them all
for prog in $float
    bspc rule -a $prog state=floating center=on
end

## And float every window that enters desktop IV via the following script
floating_desktop &

# Launcher type things - they are sticky without a border
bspc rule -a Ulauncher state=floating sticky=on border=off

# https://github.com/baskerville/bspwm/tree/master/examples/external_rules
bspc config external_rules_command external_rules &

# JetBrains & Java hack - they don't recognise bspwm as a window manager
wmname LG3D &
